spring.application.name=job-scheduler

spring.security.user.name=rohan
spring.security.user.password=marya

spring.datasource.url=jdbc:postgresql://localhost:5432/job-scheduler
spring.datasource.username=postgres
spring.datasource.password=1507

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=TRACE

jwt.secret=ThisIsMyVeryLongSecretKeyForDevelopment123456789
jwt.expiration=3600000