spring.application.name=job-scheduler

spring.security.user.name=rohan
spring.security.user.password=marya

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=TRACE

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}